<?php

namespace Formhawk\Admin;

use Formhawk\Analytics\AnalyticsRepository;
use Formhawk\Analytics\FormRepository;
use Formhawk\Analytics\HealthEvaluator;
use Formhawk\Analytics\EvidenceMetrics;
use Formhawk\Domain\ProviderCatalog;
use Formhawk\Infrastructure\IngestionDiagnostics;
use Formhawk\Infrastructure\Activator;
use Formhawk\Infrastructure\Database;
use Formhawk\Integrations\IntegrationRegistry;

final class Admin {
	private $forms;
	private $analytics;
	private $integrations;

	public function __construct( FormRepository $forms, IntegrationRegistry $integrations = null ) {
		$this->forms        = $forms;
		$this->analytics    = new AnalyticsRepository();
		$this->integrations = $integrations;
	}

	public function register() {
		add_action( 'admin_menu', array( $this, 'menu' ) );
		add_action( 'admin_enqueue_scripts', array( $this, 'assets' ) );
		add_action( 'admin_post_formhawk_save_settings', array( $this, 'save_settings' ) );
		add_action( 'admin_post_formhawk_test_mail', array( $this, 'test_mail' ) );
		add_filter( 'plugin_action_links_' . plugin_basename( FORMHAWK_FILE ), array( $this, 'action_links' ) );
	}

	public function menu() {
		add_menu_page(
			__( 'Formhawk', 'formhawk' ),
			__( 'Formhawk', 'formhawk' ),
			'manage_options',
			'formhawk',
			array( $this, 'render' ),
			'dashicons-chart-area',
			58
		);
	}

	public function assets( $hook ) {
		if ( 'toplevel_page_formhawk' !== $hook ) {
			return;
		}
		wp_enqueue_style( 'formhawk-admin', FORMHAWK_URL . 'assets/css/admin.css', array(), FORMHAWK_VERSION );
	}

	public function action_links( $links ) {
		array_unshift( $links, '<a href="' . esc_url( admin_url( 'admin.php?page=formhawk' ) ) . '">' . esc_html__( 'Dashboard', 'formhawk' ) . '</a>' );
		return $links;
	}

	public function render() {
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( esc_html__( 'You do not have permission to access Formhawk.', 'formhawk' ) );
		}

		$this->notice();

		// phpcs:ignore WordPress.Security.NonceVerification.Recommended, WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- Read-only raw input is type-checked and normalized on the next line.
		$form_id = isset( $_GET['form_id'] ) ? wp_unslash( $_GET['form_id'] ) : 0;
		$form_id = is_scalar( $form_id ) ? absint( $form_id ) : 0;
		if ( $form_id ) {
			$this->render_form( $form_id );
			return;
		}

		// phpcs:ignore WordPress.Security.NonceVerification.Recommended, WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- Read-only raw input is type-checked and sanitized on the next line.
		$tab = isset( $_GET['tab'] ) ? wp_unslash( $_GET['tab'] ) : 'overview';
		$tab = is_scalar( $tab ) ? sanitize_key( (string) $tab ) : 'overview';
		$this->header( $tab );

		switch ( $tab ) {
			case 'diagnostics':
				$this->render_diagnostics();
				break;
			case 'settings':
				$this->render_settings();
				break;
			default:
				$this->render_overview();
				break;
		}
		echo '</div>';
	}

	public function save_settings() {
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( esc_html__( 'You do not have permission to perform this action.', 'formhawk' ) );
		}
		check_admin_referer( 'formhawk_save_settings' );
		// phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- Raw input is type-checked and normalized on the next line.
		$days = isset( $_POST['retention_days'] ) ? wp_unslash( $_POST['retention_days'] ) : 90;
		$days = is_scalar( $days ) ? absint( $days ) : 90;
		if ( ! in_array( $days, array( 30, 90, 180, 365 ), true ) ) {
			$days = 90;
		}
		// phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- Raw input is type-checked and sanitized on the next line.
		$delete_on_uninstall = isset( $_POST['delete_on_uninstall'] ) ? wp_unslash( $_POST['delete_on_uninstall'] ) : '';
		$delete_on_uninstall = is_scalar( $delete_on_uninstall ) && '1' === sanitize_text_field( (string) $delete_on_uninstall ) ? 1 : 0;
		update_option(
			'formhawk_settings',
			array(
				'retention_days'      => $days,
				'delete_on_uninstall' => $delete_on_uninstall,
			),
			false
		);
		$this->set_notice( 'success', __( 'Settings saved.', 'formhawk' ) );
		wp_safe_redirect( admin_url( 'admin.php?page=formhawk&tab=settings' ) );
		exit;
	}

	public function test_mail() {
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( esc_html__( 'You do not have permission to perform this action.', 'formhawk' ) );
		}
		check_admin_referer( 'formhawk_test_mail' );
		$user      = wp_get_current_user();
		$recipient = $user && is_email( $user->user_email ) ? $user->user_email : get_option( 'admin_email' );
		$result    = wp_mail(
			$recipient,
			__( 'Formhawk mail health check', 'formhawk' ),
			__( 'This message was generated by a manual Formhawk mail health check. Formhawk does not store the recipient or message content.', 'formhawk' )
		);
		$this->set_notice(
			$result ? 'success' : 'error',
			$result
				? __( 'WordPress accepted the test email for sending. This confirms wp_mail() completed without an immediate error, not inbox delivery.', 'formhawk' )
				: __( 'wp_mail() reported a failure. Check your SMTP/mail configuration and the Formhawk mail health status below.', 'formhawk' )
		);
		wp_safe_redirect( admin_url( 'admin.php?page=formhawk&tab=diagnostics' ) );
		exit;
	}

	private function render_overview() {
		$days     = $this->days();
		$page     = $this->page_number();
		$per_page = 50;
		$totals   = $this->analytics->overview_totals( $days );
		$page     = min( $page, max( 1, (int) ceil( $totals['forms'] / $per_page ) ) );
		$rows     = $this->analytics->overview( $days, $page, $per_page );
		$rate     = EvidenceMetrics::ratio( $totals['eligible_confirmed_successes'], $totals['eligible_starts'] );
		?>
		<div class="fh-toolbar">
			<div>
				<h2><?php esc_html_e( 'Forms', 'formhawk' ); ?></h2>
				<p><?php esc_html_e( 'Conversion and health at a glance. No field values are collected.', 'formhawk' ); ?></p>
			</div>
			<?php $this->range_picker( $days ); ?>
		</div>

		<div class="fh-metrics">
			<?php $this->metric( __( 'Forms tracked', 'formhawk' ), $totals['forms'], __( 'discovered automatically', 'formhawk' ) ); ?>
			<?php $this->metric( __( 'Views', 'formhawk' ), $totals['views'], __( 'entered the viewport', 'formhawk' ) ); ?>
			<?php $this->metric( __( 'Started', 'formhawk' ), $totals['starts'], __( 'first interaction', 'formhawk' ) ); ?>
			<?php $this->metric( __( 'Submit attempts', 'formhawk' ), $totals['submit_attempts'], __( 'browser-observed, all forms', 'formhawk' ) ); ?>
			<?php $this->metric( __( 'Observed HTML attempts', 'formhawk' ), $totals['observed_generic_attempts'], __( 'backend outcome unknown', 'formhawk' ) ); ?>
			<?php $this->metric( __( 'Confirmed successes', 'formhawk' ), $totals['eligible_confirmed_successes'], __( 'provider-confirmed', 'formhawk' ) ); ?>
			<?php $this->metric( __( 'Confirmed conversion', 'formhawk' ), $this->rate_label( $rate ), __( 'confirmed / starts, supported providers only', 'formhawk' ) ); ?>
		</div>

		<div class="fh-card fh-table-card">
			<?php if ( empty( $rows ) ) : ?>
				<div class="fh-empty">
					<span class="dashicons dashicons-chart-area"></span>
					<h3><?php esc_html_e( 'Waiting for form traffic', 'formhawk' ); ?></h3>
					<p><?php esc_html_e( 'Formhawk is active. Visit a frontend page containing a form; it will appear here automatically when the form enters the visitor viewport.', 'formhawk' ); ?></p>
				</div>
			<?php else : ?>
				<table class="widefat fixed striped fh-table">
					<thead><tr>
						<th scope="col"><?php esc_html_e( 'Form', 'formhawk' ); ?></th>
						<th scope="col"><?php esc_html_e( 'Health', 'formhawk' ); ?></th>
						<th scope="col"><?php esc_html_e( 'Views', 'formhawk' ); ?></th>
						<th scope="col"><?php esc_html_e( 'Started', 'formhawk' ); ?></th>
						<th scope="col"><?php esc_html_e( 'Attempts', 'formhawk' ); ?></th>
						<th scope="col"><?php esc_html_e( 'Confirmed successes', 'formhawk' ); ?></th>
						<th scope="col"><?php esc_html_e( 'Confirmed conversion', 'formhawk' ); ?></th>
						<th scope="col"><?php esc_html_e( 'Abandonment', 'formhawk' ); ?></th>
						<th scope="col"><?php esc_html_e( 'Last success', 'formhawk' ); ?></th>
					</tr></thead>
					<tbody>
					<?php
					foreach ( $rows as $row ) :
						$health = HealthEvaluator::evaluate( $row );
						$conv   = HealthEvaluator::conversion_rate( $row );
						$ab     = HealthEvaluator::abandonment_rate( $row );
						$url    = add_query_arg(
							array(
								'page'    => 'formhawk',
								'form_id' => absint( $row['id'] ),
								'days'    => $days,
							),
							admin_url( 'admin.php' )
						);
						?>
						<tr>
							<td>
								<a class="fh-form-link" href="<?php echo esc_url( $url ); ?>"><?php echo esc_html( $this->form_title( $row ) ); ?></a>
								<div class="fh-muted"><?php echo esc_html( $this->provider_label( $row['provider'] ) . ' · ' . $row['page_path'] ); ?></div>
							</td>
							<td><?php $this->status( $health ); ?></td>
							<td><?php echo esc_html( number_format_i18n( $row['views'] ) ); ?></td>
							<td><?php echo esc_html( number_format_i18n( $row['starts'] ) ); ?></td>
							<td><?php echo esc_html( number_format_i18n( $row['submit_attempts'] ) ); ?></td>
							<td><?php echo esc_html( $this->confirmed_label( $row ) ); ?></td>
							<td><strong><?php echo esc_html( $this->rate_label( $conv ) ); ?></strong></td>
							<td><?php echo esc_html( number_format_i18n( $ab, 1 ) . '%' ); ?></td>
							<td><?php echo esc_html( $this->relative_time( $row['last_success_at'] ) ); ?></td>
						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
			<?php endif; ?>
		</div>
		<?php $this->overview_pagination( $page, $per_page, $totals['forms'], $days ); ?>
		<?php
	}

	private function render_form( $form_id ) {
		$form = $this->forms->find( $form_id );
		if ( ! $form ) {
			wp_die( esc_html__( 'Form not found.', 'formhawk' ) );
		}
		$days       = $this->days();
		$current    = $this->analytics->form_stats( $form_id, $days );
		$previous   = $this->analytics->form_stats( $form_id, $days, true );
		$fields     = $this->analytics->field_stats( $form_id, $days );
		$placements = $this->analytics->placement_stats( $form_id, $days );
		$row        = array_merge( $form, $current );
		$health     = HealthEvaluator::evaluate( $row );
		$anomaly    = HealthEvaluator::anomaly( $row, array_merge( $form, $previous ) );
		$conv       = HealthEvaluator::conversion_rate( $row );
		$ab         = HealthEvaluator::abandonment_rate( $current );
		$avg_ms     = ! empty( $current['duration_samples'] ) ? (int) round( $current['duration_total_ms'] / $current['duration_samples'] ) : 0;
		?>
		<div class="wrap fh-wrap">
			<div class="fh-detail-head">
				<div>
					<a class="fh-back" href="
					<?php
					echo esc_url(
						add_query_arg(
							array(
								'page' => 'formhawk',
								'days' => $days,
							),
							admin_url( 'admin.php' )
						)
					);
					?>
												">← <?php esc_html_e( 'All forms', 'formhawk' ); ?></a>
					<h1><?php echo esc_html( $this->form_title( $form ) ); ?></h1>
					<p><?php echo esc_html( $this->provider_label( $form['provider'] ) . ' · ' . $form['page_path'] ); ?></p>
				</div>
				<div class="fh-detail-actions"><?php $this->status( $health, true ); ?><?php $this->range_picker( $days, $form_id ); ?></div>
			</div>

			<?php if ( $anomaly ) : ?>
				<?php
				/* translators: %s: percentage drop in form conversion. */
				$drop_message = sprintf( __( 'Confirmed conversion dropped %s%%.', 'formhawk' ), number_format_i18n( $anomaly['drop'], 0 ) );
				/* translators: 1: current conversion percentage, 2: previous comparable-period conversion percentage. */
				$period_message = sprintf( __( 'Current period: %1$s%%. Previous comparable period: %2$s%%.', 'formhawk' ), number_format_i18n( $anomaly['current_rate'], 1 ), number_format_i18n( $anomaly['previous_rate'], 1 ) );
				?>
				<div class="fh-alert fh-alert-warning"><strong><?php echo esc_html( $drop_message ); ?></strong> <?php echo esc_html( $period_message ); ?></div>
			<?php endif; ?>

			<div class="fh-metrics fh-metrics-detail">
				<?php $this->metric( __( 'Views', 'formhawk' ), $current['views'], __( 'form viewed', 'formhawk' ) ); ?>
				<?php $this->metric( __( 'Started', 'formhawk' ), $current['starts'], $this->percent_of( $current['starts'], $current['views'] ) . ' ' . __( 'of views', 'formhawk' ) ); ?>
				<?php $this->metric( __( 'Submit attempts', 'formhawk' ), $current['submit_attempts'], __( 'browser-observed', 'formhawk' ) ); ?>
				<?php $this->metric( __( 'Confirmed successes', 'formhawk' ), $this->confirmed_label( $row ), __( 'provider-confirmed', 'formhawk' ) ); ?>
				<?php $this->metric( __( 'Confirmed conversion', 'formhawk' ), $this->rate_label( $conv ), __( 'confirmed / starts', 'formhawk' ) ); ?>
				<?php $this->metric( __( 'Observed attempt rate', 'formhawk' ), $this->rate_label( EvidenceMetrics::observed_attempt_rate( $row ) ), __( 'browser attempts / starts', 'formhawk' ) ); ?>
				<?php $this->metric( __( 'Abandoned', 'formhawk' ), $current['abandons'], number_format_i18n( $ab, 1 ) . '% ' . __( 'of starts', 'formhawk' ) ); ?>
				<?php $this->metric( __( 'Avg. time', 'formhawk' ), $this->duration( $avg_ms ), __( 'started → submit/leave', 'formhawk' ) ); ?>
			</div>

			<p class="fh-note"><?php esc_html_e( 'Conversion is an aggregate ratio, not a linked visitor funnel. N/A means unavailable evidence, no denominator, or more outcomes than recorded starts. Browser validation friction is shown as reports, not a failure rate: native validation can block submission before a submit event exists.', 'formhawk' ); ?></p>
			<p class="fh-note"><?php esc_html_e( 'Validation rejection share = provider validation rejections / (provider validation rejections + accepted submissions), measured since the evidence upgrade. Other provider failures and unknown outcomes are excluded.', 'formhawk' ); ?></p>
			<details><summary><?php esc_html_e( 'Historical counters (legacy evidence)', 'formhawk' ); ?></summary>
				<p><?php esc_html_e( 'These frozen counters predate evidence separation and are excluded from current conversion and validation calculations.', 'formhawk' ); ?></p>
				<dl class="fh-kv"><div><dt><?php esc_html_e( 'Legacy submissions (mixed evidence)', 'formhawk' ); ?></dt><dd><?php echo esc_html( number_format_i18n( $current['submissions'] ) ); ?></dd></div>
				<div><dt><?php esc_html_e( 'Legacy validation (source unknown)', 'formhawk' ); ?></dt><dd><?php echo esc_html( number_format_i18n( $current['validation_failures'] ) ); ?></dd></div></dl>
			</details>
			<div class="fh-grid-2">
				<div class="fh-card">
					<div class="fh-card-head"><h2><?php esc_html_e( 'Conversion funnel', 'formhawk' ); ?></h2></div>
					<?php $this->funnel_row( __( 'Viewed', 'formhawk' ), $current['views'], $current['views'] ); ?>
					<?php $this->funnel_row( __( 'Started', 'formhawk' ), $current['starts'], $current['views'] ); ?>
					<?php $this->funnel_row( __( 'Browser submit attempts', 'formhawk' ), $current['submit_attempts'], $current['views'] ); ?>
				</div>
				<div class="fh-card">
					<div class="fh-card-head"><h2><?php esc_html_e( 'Health', 'formhawk' ); ?></h2></div>
					<div class="fh-health-large"><?php $this->status( $health, true ); ?><p><?php echo esc_html( $health['reason'] ); ?></p></div>
					<dl class="fh-kv">
						<div><dt><?php esc_html_e( 'Last confirmed success', 'formhawk' ); ?></dt><dd><?php echo esc_html( $this->relative_time( $form['last_success_at'] ) ); ?></dd></div>
						<div><dt><?php esc_html_e( 'Last failure', 'formhawk' ); ?></dt><dd><?php echo esc_html( $this->relative_time( $form['last_failure_at'] ) ); ?></dd></div>
						<div><dt><?php esc_html_e( 'Browser validation friction reports', 'formhawk' ); ?></dt><dd><?php echo esc_html( number_format_i18n( $current['client_validation_failures'] ) ); ?></dd></div>
						<div><dt><?php esc_html_e( 'Provider validation rejections', 'formhawk' ); ?></dt><dd><?php echo esc_html( ProviderCatalog::has_server_success( $form['provider'] ) ? number_format_i18n( $current['provider_validation_failures'] ) : __( 'N/A', 'formhawk' ) ); ?></dd></div>
						<div><dt><?php esc_html_e( 'Validation rejection share', 'formhawk' ); ?></dt><dd><?php echo esc_html( $this->rate_label( EvidenceMetrics::validation_rate( $row ) ) ); ?></dd></div>
						<div><dt><?php esc_html_e( 'Provider failures', 'formhawk' ); ?></dt><dd><?php echo esc_html( ProviderCatalog::has_server_failure( $form['provider'] ) ? number_format_i18n( $current['failures'] ) : __( 'N/A', 'formhawk' ) ); ?></dd></div>
						<div><dt><?php esc_html_e( 'Mail action successes', 'formhawk' ); ?></dt><dd><?php echo esc_html( number_format_i18n( $current['mail_successes'] ) ); ?></dd></div>
						<div><dt><?php esc_html_e( 'Mail failures', 'formhawk' ); ?></dt><dd><?php echo esc_html( number_format_i18n( $current['mail_failures'] ) ); ?></dd></div>
						<div><dt><?php esc_html_e( 'Confirmed successes', 'formhawk' ); ?></dt><dd><?php echo esc_html( $this->confirmed_label( $row ) ); ?></dd></div>
					</dl>
					<?php
					if ( ! ProviderCatalog::has_server_success( $form['provider'] ) ) :
						?>
						<p class="fh-note"><?php esc_html_e( 'Standard HTML forms expose browser submit attempts but have no universal server-side success signal. Supported form plugins use provider-confirmed lifecycle hooks.', 'formhawk' ); ?></p><?php endif; ?>
				</div>
			</div>

			<div class="fh-card fh-table-card">
				<div class="fh-card-head"><h2><?php esc_html_e( 'Placements', 'formhawk' ); ?></h2><span><?php esc_html_e( 'Performance by page path', 'formhawk' ); ?></span></div>
				<?php if ( empty( $placements ) ) : ?>
					<div class="fh-empty-mini"><?php esc_html_e( 'Placement analytics will appear after the next tracked event.', 'formhawk' ); ?></div>
				<?php else : ?>
					<table class="widefat striped fh-table">
						<thead><tr>
							<th scope="col"><?php esc_html_e( 'Page path', 'formhawk' ); ?></th>
							<th scope="col"><?php esc_html_e( 'Views', 'formhawk' ); ?></th>
							<th scope="col"><?php esc_html_e( 'Started', 'formhawk' ); ?></th>
							<th scope="col"><?php esc_html_e( 'Attempts', 'formhawk' ); ?></th>
							<th scope="col"><?php esc_html_e( 'Confirmed successes', 'formhawk' ); ?></th>
							<th scope="col"><?php esc_html_e( 'Confirmed conversion', 'formhawk' ); ?></th>
						</tr></thead>
						<tbody>
						<?php foreach ( $placements as $placement ) : ?>
							<tr>
								<td><code><?php echo esc_html( $placement['page_path'] ); ?></code></td>
								<td><?php echo esc_html( number_format_i18n( $placement['views'] ) ); ?></td>
								<td><?php echo esc_html( number_format_i18n( $placement['starts'] ) ); ?></td>
								<td><?php echo esc_html( number_format_i18n( $placement['submit_attempts'] ) ); ?></td>
								<td><?php echo esc_html( $this->confirmed_label( array_merge( $placement, array( 'provider' => $form['provider'] ) ) ) ); ?></td>
								<td><?php echo esc_html( $this->rate_label( EvidenceMetrics::confirmed_conversion( array_merge( $placement, array( 'provider' => $form['provider'] ) ) ) ) ); ?></td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>
				<?php endif; ?>
			</div>

			<div class="fh-grid-2">
				<div class="fh-card">
					<div class="fh-card-head"><h2><?php esc_html_e( 'Where people abandon', 'formhawk' ); ?></h2><span><?php esc_html_e( 'Last field before leaving', 'formhawk' ); ?></span></div>
					<?php $this->field_table( $fields, 'abandonments' ); ?>
				</div>
				<div class="fh-card">
					<div class="fh-card-head"><h2><?php esc_html_e( 'Validation friction', 'formhawk' ); ?></h2><span><?php esc_html_e( 'Errors by field', 'formhawk' ); ?></span></div>
					<h3><?php esc_html_e( 'Browser friction', 'formhawk' ); ?></h3>
					<?php $this->field_table( $fields, 'client_validation_errors' ); ?>
					<h3><?php esc_html_e( 'Provider validation', 'formhawk' ); ?></h3>
					<?php
					if ( ProviderCatalog::has_server_success( $form['provider'] ) ) {
						$this->field_table( $fields, 'provider_validation_errors' );
					} else {
						echo '<p>' . esc_html__( 'N/A: this form has no provider validation evidence.', 'formhawk' ) . '</p>'; }
					?>
					<h3><?php esc_html_e( 'Legacy validation (source unknown)', 'formhawk' ); ?></h3>
					<?php $this->field_table( $fields, 'validation_errors' ); ?>
				</div>
			</div>
		</div>
		<?php
	}

	private function render_diagnostics() {
		$mail   = get_option( 'formhawk_mail_health', array() );
		$checks = array(
			array( __( 'Analytics database', 'formhawk' ), Database::tables_exist() && Database::schema_is_current() && Database::ingestion_ready(), __( 'Schema and structural migration are complete. If this check fails, ingestion pauses and the upgrade resumes on subsequent requests.', 'formhawk' ) ),
			array( __( 'Frontend tracker', 'formhawk' ), is_readable( FORMHAWK_DIR . 'assets/js/tracker.js' ), __( 'Tracker asset is readable.', 'formhawk' ) ),
			array( __( 'REST ingestion', 'formhawk' ), function_exists( 'register_rest_route' ), __( 'WordPress REST API support is available.', 'formhawk' ) ),
			array( __( 'Data cleanup', 'formhawk' ), (bool) wp_next_scheduled( Activator::CRON_HOOK ), __( 'Daily retention cleanup is scheduled.', 'formhawk' ) ),
		);
		if ( $this->integrations ) {
			foreach ( $this->integrations->all() as $provider => $integration ) {
				if ( 'html' === $provider ) {
					continue;
				}
				$checks[] = array( $integration->label(), $integration->is_available(), __( 'Provider lifecycle integration is active.', 'formhawk' ), true );
			}
		}
		?>
		<div class="fh-toolbar"><div><h2><?php esc_html_e( 'Diagnostics', 'formhawk' ); ?></h2><p><?php esc_html_e( 'Fast checks for the Formhawk runtime and WordPress mail layer.', 'formhawk' ); ?></p></div></div>
		<div class="fh-checks">
		<?php
		foreach ( $checks as $check ) :
			$optional = ! empty( $check[3] );
			?>
			<div class="fh-card fh-check"><span class="fh-check-icon <?php echo $check[1] ? 'is-ok' : ( $optional ? 'is-neutral' : 'is-bad' ); ?>"><?php echo $check[1] ? '✓' : ( $optional ? '–' : '!' ); ?></span><div><h3><?php echo esc_html( $check[0] ); ?></h3><p><?php echo esc_html( $check[1] ? $check[2] : ( $optional ? __( 'Not active. This is optional.', 'formhawk' ) : __( 'Check failed.', 'formhawk' ) ) ); ?></p></div></div>
		<?php endforeach; ?>
		</div>

		<div class="fh-card">
			<h2><?php esc_html_e( 'Ingestion diagnostics (today, UTC)', 'formhawk' ); ?></h2>
			<p><?php esc_html_e( 'Site-wide aggregate counters. No IP addresses, request payloads or visitor identifiers are retained. Event counts cover bounded, parseable batches, including throttled requests. Oversized or unparseable bodies are counted as requests only.', 'formhawk' ); ?></p>
			<dl class="fh-kv">
			<?php
			$diagnostic_labels = array(
				'rejected_events'             => __( 'Rejected events', 'formhawk' ),
				'rejected_requests'           => __( 'Rejected requests', 'formhawk' ),
				'throttled_events'            => __( 'Throttled events', 'formhawk' ),
				'throttled_requests'          => __( 'Throttled requests', 'formhawk' ),
				'cardinality_rejected_events' => __( 'Cardinality-rejected events', 'formhawk' ),
				'storage_rejected_events'     => __( 'Storage/admission unavailable events', 'formhawk' ),
			);
			foreach ( ( new IngestionDiagnostics() )->today() as $key => $value ) :
				?>
				<div><dt><?php echo esc_html( $diagnostic_labels[ $key ] ); ?></dt><dd><?php echo esc_html( number_format_i18n( $value ) ); ?></dd></div>
			<?php endforeach; ?>
			</dl>
		</div>
		<div class="fh-card fh-mail-card">
			<div><h2><?php esc_html_e( 'WordPress mail health', 'formhawk' ); ?></h2><p><?php esc_html_e( 'Formhawk listens to wp_mail() success/failure hooks globally but never stores recipients, subjects, message bodies or attachments.', 'formhawk' ); ?></p></div>
			<dl class="fh-kv">
				<div><dt><?php esc_html_e( 'Last wp_mail success', 'formhawk' ); ?></dt><dd><?php echo esc_html( $this->relative_time( isset( $mail['last_success'] ) ? $mail['last_success'] : null ) ); ?></dd></div>
				<div><dt><?php esc_html_e( 'Last wp_mail failure', 'formhawk' ); ?></dt><dd><?php echo esc_html( $this->relative_time( isset( $mail['last_failure'] ) ? $mail['last_failure'] : null ) ); ?></dd></div>
				<div><dt><?php esc_html_e( 'Observed successes', 'formhawk' ); ?></dt><dd><?php echo esc_html( number_format_i18n( isset( $mail['successes'] ) ? $mail['successes'] : 0 ) ); ?></dd></div>
				<div><dt><?php esc_html_e( 'Observed failures', 'formhawk' ); ?></dt><dd><?php echo esc_html( number_format_i18n( isset( $mail['failures'] ) ? $mail['failures'] : 0 ) ); ?></dd></div>
			</dl>
			<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>">
				<input type="hidden" name="action" value="formhawk_test_mail">
				<?php wp_nonce_field( 'formhawk_test_mail' ); ?>
				<?php submit_button( __( 'Send test email to me', 'formhawk' ), 'secondary', 'submit', false ); ?>
			</form>
			<p class="fh-note"><?php esc_html_e( 'A successful wp_mail() call means WordPress/PHPMailer accepted the message for sending. It does not prove final inbox delivery.', 'formhawk' ); ?></p>
		</div>
		<?php
	}

	private function rate_label( $rate ) {
		return null === $rate ? __( 'N/A', 'formhawk' ) : number_format_i18n( $rate, 1 ) . '%';
	}

	private function confirmed_label( array $row ) {
		return ProviderCatalog::has_server_success( $row['provider'] ) ? number_format_i18n( $row['confirmed_successes'] ) : __( 'N/A', 'formhawk' );
	}

	private function render_settings() {
		$settings            = get_option( 'formhawk_settings', array() );
		$days                = isset( $settings['retention_days'] ) ? absint( $settings['retention_days'] ) : 90;
		$delete_on_uninstall = ! empty( $settings['delete_on_uninstall'] );
		?>
		<div class="fh-toolbar"><div><h2><?php esc_html_e( 'Settings', 'formhawk' ); ?></h2><p><?php esc_html_e( 'The defaults are intentionally small and privacy-first.', 'formhawk' ); ?></p></div></div>
		<div class="fh-grid-2">
			<div class="fh-card">
				<h2><?php esc_html_e( 'Data retention', 'formhawk' ); ?></h2>
				<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>">
					<input type="hidden" name="action" value="formhawk_save_settings">
					<?php wp_nonce_field( 'formhawk_save_settings' ); ?>
					<label class="fh-label" for="retention_days"><?php esc_html_e( 'Keep daily aggregates for', 'formhawk' ); ?></label>
					<select name="retention_days" id="retention_days">
						<?php foreach ( array( 30, 90, 180, 365 ) as $option ) : ?>
							<?php
							/* translators: %d: number of days analytics aggregates are retained. */
							$retention_label = sprintf( _n( '%d day', '%d days', $option, 'formhawk' ), $option );
							?>
						<option value="<?php echo esc_attr( (string) $option ); ?>" <?php selected( $days, $option ); ?>><?php echo esc_html( $retention_label ); ?></option>
						<?php endforeach; ?>
					</select>
					<label class="fh-checkbox"><input type="checkbox" name="delete_on_uninstall" value="1" <?php checked( $delete_on_uninstall ); ?>> <?php esc_html_e( 'Delete all Formhawk analytics data when the plugin is deleted.', 'formhawk' ); ?></label>
					<?php submit_button( __( 'Save settings', 'formhawk' ) ); ?>
				</form>
			</div>
			<div class="fh-card">
				<h2><?php esc_html_e( 'Privacy model', 'formhawk' ); ?></h2>
				<ul class="fh-privacy-list">
					<li>✓ <?php esc_html_e( 'No cookies.', 'formhawk' ); ?></li>
					<li>✓ <?php esc_html_e( 'No IP addresses stored.', 'formhawk' ); ?></li>
					<li>✓ <?php esc_html_e( 'No visitor user IDs or visitor identifiers stored in analytics.', 'formhawk' ); ?></li>
					<li>✓ <?php esc_html_e( 'No form field values stored.', 'formhawk' ); ?></li>
					<li>✓ <?php esc_html_e( 'No email subjects, recipients or bodies stored.', 'formhawk' ); ?></li>
					<li>✓ <?php esc_html_e( 'No external analytics service. Aggregates stay in this WordPress database.', 'formhawk' ); ?></li>
				</ul>
				<p class="fh-note"><?php esc_html_e( 'Field names/labels and page paths are stored so the dashboard can identify friction points. They describe the form structure, never the visitor response.', 'formhawk' ); ?></p>
			</div>
		</div>
		<?php
	}

	private function header( $active ) {
		?>
		<div class="wrap fh-wrap">
			<div class="fh-brand"><div class="fh-logo">FH</div><div><h1>Formhawk</h1><p><?php esc_html_e( 'Know when forms stop working — and where visitors give up.', 'formhawk' ); ?></p></div></div>
			<nav class="nav-tab-wrapper fh-tabs">
				<?php
				foreach ( array(
					'overview'    => __( 'Overview', 'formhawk' ),
					'diagnostics' => __( 'Diagnostics', 'formhawk' ),
					'settings'    => __( 'Settings', 'formhawk' ),
				) as $tab => $label ) :
					?>
					<a class="nav-tab <?php echo $active === $tab ? 'nav-tab-active' : ''; ?>" href="
					<?php
					echo esc_url(
						add_query_arg(
							array(
								'page' => 'formhawk',
								'tab'  => $tab,
							),
							admin_url( 'admin.php' )
						)
					);
					?>
										"><?php echo esc_html( $label ); ?></a>
				<?php endforeach; ?>
			</nav>
		<?php
	}

	private function range_picker( $days, $form_id = 0 ) {
		echo '<div class="fh-range">';
		foreach ( array( 7, 30, 90 ) as $option ) {
			$args = array(
				'page' => 'formhawk',
				'days' => $option,
			);
			if ( $form_id ) {
				$args['form_id'] = $form_id;
			}
			$class = $days === $option ? 'is-active' : '';
			echo '<a class="' . esc_attr( $class ) . '" href="' . esc_url( add_query_arg( $args, admin_url( 'admin.php' ) ) ) . '">' . esc_html( $option . 'd' ) . '</a>';
		}
		echo '</div>';
	}

	private function metric( $label, $value, $hint ) {
		echo '<div class="fh-card fh-metric"><span>' . esc_html( $label ) . '</span><strong>' . esc_html( is_numeric( $value ) ? number_format_i18n( $value ) : $value ) . '</strong><small>' . esc_html( $hint ) . '</small></div>';
	}

	private function status( array $health, $large = false ) {
		echo '<span class="fh-status fh-status-' . esc_attr( $health['status'] ) . ( $large ? ' is-large' : '' ) . '"><i></i>' . esc_html( $health['label'] ) . '</span>';
	}

	private function funnel_row( $label, $value, $base ) {
		$percent = $base > 0 ? min( 100, ( $value / $base ) * 100 ) : 0;
		echo '<div class="fh-funnel-row"><div><span>' . esc_html( $label ) . '</span><strong>' . esc_html( number_format_i18n( $value ) ) . '</strong></div><div class="fh-bar"><i style="width:' . esc_attr( number_format( $percent, 2, '.', '' ) ) . '%"></i></div><small>' . esc_html( number_format_i18n( $percent, 1 ) . '%' ) . '</small></div>';
	}

	private function field_table( array $fields, $metric ) {
		$filtered = array_values(
			array_filter(
				$fields,
				static function ( $row ) use ( $metric ) {
					return ! empty( $row[ $metric ] );
				}
			)
		);
		if ( empty( $filtered ) ) {
			echo '<div class="fh-empty-mini">' . esc_html__( 'No data yet.', 'formhawk' ) . '</div>';
			return;
		}
		echo '<div class="fh-field-list">';
		foreach ( array_slice( $filtered, 0, 8 ) as $field ) {
			$label = $field['field_label'] ? $field['field_label'] : $field['field_key'];
			$count = absint( $field[ $metric ] );
			$rate  = 'abandonments' === $metric && ! empty( $field['interactions'] ) ? ( $count / absint( $field['interactions'] ) ) * 100 : null;
			echo '<div class="fh-field-row"><div><strong>' . esc_html( $label ) . '</strong><span>' . esc_html( $field['field_key'] ) . '</span></div><div><strong>' . esc_html( number_format_i18n( $count ) ) . '</strong>' . ( null !== $rate ? '<span>' . esc_html( number_format_i18n( $rate, 1 ) . '%' ) . '</span>' : '' ) . '</div></div>';
		}
		echo '</div>';
	}

	private function days() {
		// phpcs:ignore WordPress.Security.NonceVerification.Recommended, WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- Read-only raw input is type-checked and normalized on the next line.
		$days = isset( $_GET['days'] ) ? wp_unslash( $_GET['days'] ) : 30;
		$days = is_scalar( $days ) ? absint( $days ) : 30;
		return in_array( $days, array( 7, 30, 90 ), true ) ? $days : 30;
	}

	private function page_number() {
		// phpcs:ignore WordPress.Security.NonceVerification.Recommended, WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- Read-only raw input is type-checked and normalized on the next line.
		$page = isset( $_GET['paged'] ) ? wp_unslash( $_GET['paged'] ) : 1;
		return is_scalar( $page ) ? max( 1, absint( $page ) ) : 1;
	}

	private function overview_pagination( $page, $per_page, $total, $days ) {
		$total_pages = (int) ceil( absint( $total ) / max( 1, absint( $per_page ) ) );
		if ( $total_pages <= 1 ) {
			return;
		}

		$links = paginate_links(
			array(
				'base'      => str_replace(
					'999999999',
					'%#%',
					add_query_arg(
						array(
							'page'  => 'formhawk',
							'days'  => absint( $days ),
							'paged' => 999999999,
						),
						admin_url( 'admin.php' )
					)
				),
				'format'    => '',
				'current'   => min( max( 1, absint( $page ) ), $total_pages ),
				'total'     => $total_pages,
				'mid_size'  => 2,
				'prev_text' => __( 'Previous', 'formhawk' ),
				'next_text' => __( 'Next', 'formhawk' ),
				'type'      => 'list',
			)
		);
		if ( $links ) {
			echo '<nav class="fh-pagination" aria-label="' . esc_attr__( 'Forms pagination', 'formhawk' ) . '">' . wp_kses_post( $links ) . '</nav>';
		}
	}

	private function form_title( array $row ) {
		if ( ! empty( $row['title'] ) ) {
			return $row['title'];
		}
		if ( 'cf7' === $row['provider'] ) {
			/* translators: %s: Contact Form 7 form ID. */
			return sprintf( __( 'Contact Form 7 #%s', 'formhawk' ), $row['provider_form_id'] );
		}
		if ( 'wpforms' === $row['provider'] ) {
			/* translators: %s: WPForms form ID. */
			return sprintf( __( 'WPForms #%s', 'formhawk' ), $row['provider_form_id'] );
		}
		if ( 'elementor' === $row['provider'] ) {
			/* translators: %s: Elementor document and widget identity. */
			return sprintf( __( 'Elementor form %s', 'formhawk' ), $row['provider_form_id'] );
		}
		/* translators: %s: page path containing the HTML form. */
		return sprintf( __( 'HTML form · %s', 'formhawk' ), $row['page_path'] );
	}

	private function provider_label( $provider ) {
		return $this->integrations ? $this->integrations->label( $provider ) : strtoupper( (string) $provider );
	}

	private function percent_of( $value, $base ) {
		return number_format_i18n( $base > 0 ? ( $value / $base ) * 100 : 0, 1 ) . '%';
	}

	private function duration( $ms ) {
		if ( $ms <= 0 ) {
			return '—';
		}
		$seconds = (int) round( $ms / 1000 );
		if ( $seconds < 60 ) {
			/* translators: %d: number of seconds spent interacting with a form. */
			return sprintf( _n( '%d sec', '%d sec', $seconds, 'formhawk' ), $seconds );
		}
		$minutes = (int) floor( $seconds / 60 );
		$remain  = $seconds % 60;
		return sprintf( '%dm %02ds', $minutes, $remain );
	}

	private function relative_time( $datetime ) {
		if ( empty( $datetime ) ) {
			return '—';
		}
		$site_datetime = date_create_immutable_from_format( 'Y-m-d H:i:s', $datetime, wp_timezone() );
		if ( ! $site_datetime ) {
			return '—';
		}
		/* translators: %s: human-readable time difference, for example "5 minutes". */
		return sprintf( __( '%s ago', 'formhawk' ), human_time_diff( $site_datetime->getTimestamp(), current_datetime()->getTimestamp() ) );
	}


	private function set_notice( $type, $message ) {
		set_transient(
			'formhawk_notice_' . get_current_user_id(),
			array(
				'type'    => $type,
				'message' => $message,
			),
			MINUTE_IN_SECONDS
		);
	}

	private function notice() {
		$key    = 'formhawk_notice_' . get_current_user_id();
		$notice = get_transient( $key );
		if ( ! is_array( $notice ) || empty( $notice['message'] ) ) {
			return;
		}
		delete_transient( $key );
		$class = 'error' === $notice['type'] ? 'notice notice-error is-dismissible' : 'notice notice-success is-dismissible';
		echo '<div class="' . esc_attr( $class ) . '"><p>' . esc_html( $notice['message'] ) . '</p></div>';
	}
}
